In [2]:
import torch
from torch import nn
from torch.nn import functional as F

torch.manual_seed(1337)

In [3]:
B, T, C = 4, 8, 6
x = torch.randn(B, T, C)
x

tensor([[[ 0.1808, -0.0700, -0.3596, -0.9152,  0.6258,  0.0255],
         [ 0.9545,  0.0643,  0.3612,  1.1679, -1.3499, -0.5102],
         [ 0.2360, -0.2398, -0.9211,  1.5433,  1.3488, -0.1396],
         [ 0.2858,  0.9651, -2.0371,  0.4931,  1.4870,  0.5910],
         [ 0.1260, -1.5627, -1.1601, -0.3348,  0.4478, -0.8016],
         [ 1.5236,  2.5086, -0.6631, -0.2513,  1.0101,  0.1215],
         [ 0.1584,  1.1340, -1.1539, -0.2984, -0.5075, -0.9239],
         [ 0.5467, -1.4948, -1.2057,  0.5718, -0.5974, -0.6937]],

        [[ 1.6455, -0.8030,  1.3514, -0.2759, -1.5108,  2.1048],
         [ 2.7630, -1.7465,  1.4516, -1.5103,  0.8212, -0.2115],
         [ 0.7789,  1.5333,  1.6097, -0.4032, -0.8345,  0.5978],
         [-0.0514, -0.0646, -0.4970,  0.4658, -0.2573, -1.0673],
         [ 2.0089, -0.5370,  0.2228,  0.6971, -1.4267,  0.9059],
         [ 0.1446,  0.2280,  2.4900, -1.2237,  1.0107,  0.5560],
         [-1.5935, -1.2706,  0.6903, -0.1961,  0.3449, -0.3419],
         [ 0.4759, -0.7

In [4]:
tril = torch.tril(torch.ones(T, T))
tril

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
wei = torch.zeros(T, T)
wei = wei.masked_fill(tril == 0, float('-inf'))
wei

tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
wei = F.softmax(wei, dim=-1)
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [10]:
wei @ x

tensor([[[ 1.8077e-01, -6.9988e-02, -3.5962e-01, -9.1520e-01,  6.2577e-01,
           2.5510e-02],
         [ 5.6764e-01, -2.8198e-03,  7.6354e-04,  1.2634e-01, -3.6206e-01,
          -2.4233e-01],
         [ 4.5708e-01, -8.1806e-02, -3.0653e-01,  5.9866e-01,  2.0823e-01,
          -2.0810e-01],
         [ 4.1426e-01,  1.7993e-01, -7.3918e-01,  5.7228e-01,  5.2792e-01,
          -8.3188e-03],
         [ 3.5661e-01, -1.6860e-01, -8.2337e-01,  3.9085e-01,  5.1189e-01,
          -1.6698e-01],
         [ 5.5111e-01,  2.7760e-01, -7.9666e-01,  2.8383e-01,  5.9494e-01,
          -1.1890e-01],
         [ 4.9501e-01,  3.9995e-01, -8.4769e-01,  2.0066e-01,  4.3744e-01,
          -2.3390e-01],
         [ 5.0147e-01,  1.6311e-01, -8.9244e-01,  2.4705e-01,  3.0809e-01,
          -2.9137e-01]],

        [[ 1.6455e+00, -8.0299e-01,  1.3514e+00, -2.7592e-01, -1.5108e+00,
           2.1048e+00],
         [ 2.2042e+00, -1.2748e+00,  1.4015e+00, -8.9310e-01, -3.4484e-01,
           9.4662e-01],
        