In [1]:
%load_ext autoreload
%autoreload 2

In [ ]:
# import v3
# v3.main()

In [1]:
import torch
from layernorm import LayerNorm

In [3]:
torch.manual_seed(1337)
d = 100
b = 32
module = LayerNorm(d)
x = torch.randn(b, d) # batch size 32 of 100 dimensional vectors
print(x.shape)
print(x[1,:])
# print(x)
x = module(x)
print(x.shape)
print(x[1,:])
# print(x[1,:].shape)

torch.Size([32, 100])
tensor([ 0.0315, -0.7419, -0.2978,  0.0172, -0.1772, -0.1334,  0.2940,  1.3850,
         0.1209,  2.5418, -0.6405, -1.9740, -0.3296,  0.0080,  0.9262, -1.8846,
         0.1670,  0.4586, -1.7662,  0.5860,  1.7510,  0.2807,  0.3110, -0.6538,
        -0.6576,  0.3184, -0.5496, -1.4649, -2.0555,  1.8275,  1.3035, -0.4501,
         1.3471,  1.6910, -0.1244, -1.6824, -0.0266,  0.0740,  1.0517,  0.6779,
         0.3067, -0.7472,  0.7435,  0.8877,  2.2874,  0.9611, -1.5297, -0.2912,
        -0.1140, -0.3137, -0.6293,  1.1385, -0.9913,  0.1700,  1.2249, -0.2345,
        -1.0572, -0.6543,  1.5909, -0.6995, -0.8961,  0.0662, -0.0563,  2.3412,
        -2.7234,  0.5097, -0.8145, -0.2460,  0.0045,  2.0474, -0.1575, -0.2187,
        -1.3519, -0.0573, -1.8540, -1.3849, -0.3454, -1.1625,  0.1445,  0.1663,
         0.7507,  0.9132, -1.7277,  1.3055,  0.9593,  1.0600,  0.6299, -1.2867,
        -0.6875,  2.1382,  0.5114,  1.2191,  0.1910, -0.3425,  1.7955,  1.3915,
         1.0785, -

### Example of keepdim

In [16]:
import torch

x = torch.tensor([[1.0, 2.0, 3.0], 
                  [4.0, 5.0, 6.0]])

print(x.shape)
print(x)
mean_no_keepdim = x.mean(1)
print(mean_no_keepdim.shape)  # Output: torch.Size([2])
print(mean_no_keepdim)

torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2])
tensor([2., 5.])


In [14]:
mean_keepdim = x.mean(1, keepdim=True)
print(mean_keepdim.shape)  # Output: torch.Size([2])
print(mean_keepdim)

torch.Size([2, 1])
tensor([[2.],
        [5.]])
